CLASS zbp_i_matrix_entry DEFINITION PUBLIC ABSTRACT FINAL FOR BEHAVIOR OF zi_matrix_entry.
PUBLIC SECTION.
class-DATA cv_so_mapped TYPE RESPONSE FOR MAPPED i_salesordertp.
ENDCLASS.



CLASS ZBP_I_MATRIX_ENTRY IMPLEMENTATION.
ENDCLASS.
