* Does not work
CLASS zaf_cl_rest_petstore_model DEFINITION PUBLIC FINAL
  CREATE PUBLIC.
  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS ZAF_CL_REST_PETSTORE_MODEL IMPLEMENTATION.
ENDCLASS.
