CLASS zcl_mm_pur_s4_po_close DEFINITION PUBLIC FINAL CREATE PUBLIC.
  PUBLIC SECTION.
    INTERFACES if_badi_interface .
    INTERFACES if_mm_pur_s4_po_close .
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS ZCL_MM_PUR_S4_PO_CLOSE IMPLEMENTATION.


  METHOD if_mm_pur_s4_po_close~close.
  ENDMETHOD.
ENDCLASS.
