CLASS zcl_test_cp_rest_simple DEFINITION  PUBLIC FINAL CREATE PUBLIC FOR TESTING.
  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS ZCL_TEST_CP_REST_SIMPLE IMPLEMENTATION.
ENDCLASS.
