CLASS zbp_matrix_final DEFINITION PUBLIC ABSTRACT FINAL FOR BEHAVIOR OF zmatrix_final.
PUBLIC SECTION.
class-DATA cv_so_mapped TYPE RESPONSE FOR MAPPED I_SALESORDERTP.
*class-DATA cv_so2_mapped TYPE RESPONSE FOR MAPPED I_PurchaseOrderTP_2.
ENDCLASS.



CLASS ZBP_MATRIX_FINAL IMPLEMENTATION.
ENDCLASS.
