class ZBP_ONLINESHOPTP_000 DEFINITION PUBLIC ABSTRACT FINAL FOR BEHAVIOR OF zr_onlineshoptp_000.
PUBLIC SECTION.
  CLASS-DATA mapped_purchase_requisition TYPE response for mapped i_purchaserequisitiontp.
ENDCLASS.



CLASS ZBP_ONLINESHOPTP_000 IMPLEMENTATION.
ENDCLASS.
